# -*- coding: utf-8 -*-
"""Smart Meter Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7ZGxV33WUDOncvPXJYPcPDAtMAanpnp
"""

# Importing necessary libraries
import pandas as pd  # For data manipulation and analysis
import matplotlib.pyplot as plt  # For data visualization
from sklearn.model_selection import train_test_split  # For splitting data into training and testing sets
from sklearn.ensemble import RandomForestRegressor  # A machine learning model to predict energy consumption
from sklearn.metrics import mean_squared_error  # To evaluate the performance of the model

# Load the Indian smart meter dataset
data_india = pd.read_csv('https://www.kaggle.com/datasets/pythonafroz/electricity-smart-meter-data-from-india')  # Update with the correct URL if needed

# Preview the first few rows of the Indian dataset
print(data_india.head())  # Display the first five rows to understand the structure

# Feature selection for the Indian dataset (modify based on actual columns)
features_india = data_india[['temperature', 'humidity']]  # Assuming these features exist
target_india = data_india['consumption']  # Assuming this is the energy consumption column

# Splitting the dataset into training and testing sets
X_train_india, X_test_india, y_train_india, y_test_india = train_test_split(features_india, target_india, test_size=0.2, random_state=42)

# Initialize the model for Indian dataset
model_india = RandomForestRegressor(n_estimators=100, random_state=42)  # Create a Random Forest model

# Train the model on Indian data
model_india.fit(X_train_india, y_train_india)

# Predict energy consumption for Indian test data
y_pred_india = model_india.predict(X_test_india)

# Evaluate the model
mse_india = mean_squared_error(y_test_india, y_pred_india)
print(f'Mean Squared Error (India): {mse_india}')

# Visualize the actual vs predicted consumption for India
plt.figure(figsize=(10, 6))
plt.plot(y_test_india.values, label='Actual Consumption (India)')
plt.plot(y_pred_india, label='Predicted Consumption (India)')
plt.legend()
plt.title('Actual vs Predicted Energy Consumption (India)')
plt.xlabel('Test Data Index')
plt.ylabel('Energy Consumption (kWh)')
plt.show()